#!/usr/bin/env escript

main(_) ->
	compile(".").
	
compile(Root)->
	file:set_cwd(Root),
	make:all(),
	{ok,Cwd}=file:get_cwd(),
	{ok,Files}=file:list_dir(Cwd),
	SubDirs=[File||File<-Files,filelib:is_dir(File)],
	[compile(SubDir)||SubDir<-SubDirs],
	file:set_cwd("..").
