#!/usr/bin/env escript
%%! -sname script 

main(["start"])->
	{Cookie,NidsName} = get_start_config(),
	erlang:set_cookie(node(),Cookie),
	Nids=get_nids(NidsName),
	case exist_nids(Nids) of
		false-> io:fwrite("TRUE");
		true->io:fwrite("FALSE")
	end;
main(["stop"])->
	{Cookie,NidsName} = get_start_config(),
	erlang:set_cookie(node(),Cookie),
	Nids=get_nids(NidsName),
	case exist_nids(Nids) of
		true->rpc:call(Nids,erlang,halt,[]),
			io:fwrite("TRUE");
		false->io:fwrite("FALSE")
	end;
main(["opt"])->
	{Cookie,NidsName} = get_start_config(),
	erlang:set_cookie(node(),Cookie),
	Nids=get_nids(NidsName),
	case exist_nids(Nids) of
		true->case rpc:call(Nids,erlang,where_is,[options]) of
				undefined->io:fwrite("FALSE");
				_->{options,Nids} ! restart_window,
					io:fwrite("TRUE")
			  end;
		false->io:fwrite("FALSE")
	end;
main(["config"|T])->
	{ok,ConfigFile} = file:open("nidsStartConfig",[write]),
	{ok,VmConfig} = file:open("vm.args",[write]),
	[Cookie,NidsName] = T,
	file:write(ConfigFile,Cookie ++ ":" ++ NidsName),
	io:format(VmConfig, "~s~n", ["-setcookie " ++ Cookie]),
	io:format(VmConfig, "~s~n", ["-sname " ++ NidsName]),
	io:format(VmConfig, "~s~n", ["-detached"]),
	file:close(VmConfig),
	file:close(ConfigFile).

get_start_config()->
	{ok,ConfigFile} = file:open("nidsStartConfig",[read]),
	{ok,Configs} = file:read_line(ConfigFile),
	[Cookie,NidsName] = string:split(Configs,":",all),
	file:close(ConfigFile),
	{list_to_atom(Cookie),NidsName}.

get_nids(NidsName)->
	{ok,Name}=inet:gethostname(),
	list_to_atom(NidsName ++ "@" ++ Name).

exist_nids(Nids)->
	case net_adm:ping(Nids) of
		pong->true;
		pang->false
	end.
