#!/bin/bash

cd "PathToClonedRepo"
case $1 in
  start)
    CMD=$(./nidsManager start)
    if [[ "$CMD" == "FALSE" ]]; then
      echo "NIDS ALREADY ACTIVE\n"
    else
        ERL_FLAGS=" -args_file vm.args " rebar3 shell
    fi
    ;;
  stop)
    CMD=$(./nidsManager stop)
    if [[ "$CMD" == "FALSE" ]]; then
      echo "NIDS ALREADY INACTIVE\n"
    fi
    ;;
  opt)
    CMD=$(./nidsManager opt)
    if [[ "$CMD" == "FALSE" ]]; then
      echo "ERROR: NIDS INACTIVE OR USER PROCESS HANDLER NOT PRESENT\n"
    fi
    ;;
  config)
    ./nidsManager stop
    ./nidsManager config $2 $3
    ./nidsManager start
    ;;
  *)
  echo -n " COMMAND SEQUENCE UNKNOWN\n"
esac